### ISSUE TITLE
Don't re-fetch rust.tar.gz every single time

### ISSUE THREAD

**Issue by farcaller** [hackndev/rust-libcore#1]

**Comment by mcoffin** [comment]
To do this, we'd have to implement some way to tag the rust directory with the commit hash. Maybe just `touch` an empty file with the name of the commit hash, then check to see if the file exists. If it doesn't, delete the directory and re-download. If it exists then we already have the right version and don't need to re-download the tarball.

**Comment by bharrisau** [comment]
Or save the download with the commit version in the file name?

**Comment by mcoffin** [comment]
> Or save the download with the commit version in the file name?

It's probably a little more error prone to tag the tarball with the version than to tag the actual working directory with the version.
