### ISSUE TITLE
unable to find package `core`

### ISSUE THREAD

**Issue by blazewicz** [hackndev/rust-libcore#6]
When I try to build any package depending on this one I get this error:

> no matching package named `core` found (required by `zinc`)
> location searched: https://github.com/hackndev/rust-libcore
> version required: *

My cargo version:

> cargo 0.8.0-nightly (dd32072 2015-12-12)

**Comment by farcaller** [comment]
Reverted package rename in https://github.com/hackndev/rust-libcore/commit/8eaa99c669836853b16d7af35578992cd227bf82, will poke around crates.io later on.

**Comment by farcaller** [comment]
Actually no, I broke it again and will fix zinc side in https://github.com/hackndev/zinc/pull/360
