### ISSUE TITLE
Does not build with latest stable

### ISSUE THREAD

**Issue by Earlz** [hackndev/rust-libcore#7]
This does not build with the latest stable version of Rust:

    Compiling rust-libcore v0.0.3
    error: couldn't read "/Users/earlz/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-libcore-0.0.3/rust/src/libcore/../stdsimd/coresimd/mod.rs": No such file or directory (os error 2)

Looks related to this issue, though unsure why it fails in this package after upstream was patched https://github.com/rust-lang/rust/issues/48734

**Comment by farcaller** [comment]
Rust have a native way to cross-build the libcore, I don't think this one is needed? It's been deprecated for a few years now.
